module.exports.user_agent_edge = 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36 Edge/12.0';
module.exports.user_agent_chrome = 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36';

module.exports.compatlisturlGDR = 'http://cvlist.ie.microsoft.com/0315000/1426178821/iecompatviewlist.xml';
module.exports.compatlisturlSDR = 'http://cvlist.ie.microsoft.com/0315000/1426178821/iecompatviewlist.xml';

module.exports.check_pluginfree_options = { allowFlash: true, allowSilverlight: true, allowOthers: false };
module.exports.check_pluginfree_elements = [
    { name: 'object' },
    { name: 'embed' },
    { name: 'object param[value*=swf]', type: 'flash' },
    { name: 'object[data*=swf]', type: 'flash' },
    { name: 'object[data*=svg]' },
    { name: 'object[type*=silverlight]', type: 'silverlight' },
    { name: 'embed[src*=swf]', type: 'flash' },
    { name: 'embed[src*=svg]', type: 'flash' },
    { name: 'embed[type*=silverlight]', type: 'silverlight' }
];

module.exports.check_markup_elements = [
    { name: 'div', threshold: 0.9 },
    { name: 'canvas' },
    { name: 'a' },
    { name: 'p', threshold: 0.7 },
    { name: 'h1' },
    { name: 'h2' },
    { name: 'h3' },
    { name: 'h4' },
    { name: 'ol' },
    { name: 'ul' },
    { name: 'li' },
    { name: 'table' },
    { name: 'tr' },
    { name: 'th' },
    { name: 'td' },
    { name: 'img', threshold: 0.9 },
    { name: 'span', threshold: 0.5 },
    { name: 'form' },
    { name: 'input' },
    { name: 'textarea' },
    { name: 'button' },
    { name: 'video' },
    { name: 'audio' },
    { name: 'object' },
    { name: 'embed' }
];
module.exports.check_markup_default_threshold = 0.8;
module.exports.check_markup_exclude_list = [
    "airasiago.com.au",
    "141hongkong.com",
    "6raum.de",
    "airasiago.co.id",
    "amateurbusters.com",
    "ancora-verlagsservice.de",
    "anglinglines.com",
    "arlsura.com",
    "auslot.com",
    "auspcmarket.com.au",
    "austria.info",
    "aydinpost.com",
    "baid.com",
    "beautycarechoices.com",
    "berlinersingles.de",
    "betreut.de",
    "bikerplanet.com",
    "bikersplanet.cz",
    "blackboxxfireworks.de",
    "bn.org.uk",
    "boatsonline.com.au",
    "bruingold.com",
    "calibex.com.au",
    "camboda.com",
    "cancer.org.il",
    "cinform.com.br",
    "coastalcampingvictoria.com.au",
    "coastalholidayhomes.co.nz",
    "csgolounge.com",
    "dateland.co.il",
    "deliveryhero.com.au",
    "dogvacay.com",
    "dokochina.com",
    "domain.com.au",
    "energyaustralia.com.au",
    "english-for-students.com",
    "entrepreneurmag.co.za",
    "esny.cz",
    "expedia.co.in",
    "expedia.com.tw",
    "fan-manga-dbz.com",
    "fc-heidelberg.de",
    "fikralarim.com",
    "findcheaters.com",
    "fordforums.com.au",
    "fordmods.com",
    "gedichten-freaks.nl",
    "gites-de-france-vendee.com",
    "glamnight.fr",
    "goauto.com.au",
    "golpas.com",
    "heste-nettet.dk",
    "horchow.com",
    "hotelscombined.com.au",
    "huttonsgroup.com",
    "ichingonline.net",
    "iddaatahmin.com",
    "iledzisiaj.pl",
    "ineedescort.co.uk",
    "infinisport.fr",
    "infostud.com",
    "insel-poel.de",
    "instawebgram.com",
    "israelpost.co.il",
    "kidspot.com.au",
    "landquest.com",
    "life123.com",
    "maisregiao.com.br",
    "masters.com.au",
    "medicis-patrimoine.com",
    "mercury.com.au",
    "midlandcreditonline.com",
    "mojelekarna.cz",
    "movedancewear.com",
    "nasinsurance.com.au",
    "nationalehulpgids.nl",
    "no-minimum.com",
    "okalpha.com",
    "paardekooper.nl",
    "porse.cz",
    "portraitprofessional.com",
    "positiivarit.fi",
    "postil.com",
    "raft.cz",
    "raidom.bg",
    "reise-ecke.de",
    "resultados-ya.com",
    "ronnie.cz",
    "rsabi.org.uk",
    "simplydoorhandles.co.uk",
    "solostocks.com.br",
    "solostocks.fr",
    "starnow.com.au",
    "stilartmoebel.de",
    "swisstruck.ch",
    "tchibo.cz",
    "thecraftynut.com.au",
    "thinkspain.com",
    "tiendanaranja.com",
    "tjoob.com",
    "topfong.com",
    "tostudy.co.il",
    "tous-a-poil.com",
    "tracker-rms.com",
    "tradervs.com.au",
    "tradetrucks.com.au",
    "trivago.com.au",
    "trivago.com.co",
    "tuperro.com.mx",
    "twgaze.co.uk",
    "vanomobil.be",
    "ving.no",
    "vitoriabijouterias.com.br",
    "voy.com",
    "vvsochbad.se",
    "waffenboerse.ch",
    "webcambordeel.nl",
    "westrealestate.com.au",
    "wireless1.com.au",
    "yahoo7.com.au",
    "yelp.co.jp",
    "yelp.de",
    "youtube.com.au",
    "yuportal.net",
    "zoopla.co.uk"
];

module.exports.storage_account_name = 'sitesscannertest';
module.exports.storage_account_key = 'UWsqiL6p4I23OHCvv49qikhm8YwqruuqML/b5EEH1TK5IUhsGjRQKOccHhQ8C1MiR2GUc4Gm12NAIYLOfwrZow==';

if (process.env.Storage_AccountName)
    module.exports.storage_account_name = process.env.Storage_AccountName;

if (process.env.Storage_AccessKey)
    module.exports.storage_account_key = process.env.Storage_AccessKey;

module.exports.website_list_container_name = 'dailyscan';
module.exports.prefix = 'http://sites-scanner.azurewebsites.net/api/v2/scan?url=http://';